// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jTRMtlf3BB1JABeubsZnece1oaE7yu0',
    appId: '1:173326883920:web:777049f57ee60edff74555',
    messagingSenderId: '173326883920',
    projectId: 'b-callio',
    authDomain: 'b-callio.firebaseapp.com',
    storageBucket: 'b-callio.firebasestorage.app',
    measurementId: 'G-1S4J11RG5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzXQxqAW2Vbd3llGWU0Wq59OGF3X3298',
    appId: '1:173326883920:android:22571e3c8dbf9e3cf74555',
    messagingSenderId: '173326883920',
    projectId: 'b-callio',
    storageBucket: 'b-callio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5iHolWbfsgl9l4MjDMtxSOdrlK4IoRU',
    appId: '1:173326883920:ios:e25913be9c4cd1cbf74555',
    messagingSenderId: '173326883920',
    projectId: 'b-callio',
    storageBucket: 'b-callio.firebasestorage.app',
    iosBundleId: 'com.elite.bcalio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5iHolWbfsgl9l4MjDMtxSOdrlK4IoRU',
    appId: '1:173326883920:ios:160cfa42442dd0cef74555',
    messagingSenderId: '173326883920',
    projectId: 'b-callio',
    storageBucket: 'b-callio.firebasestorage.app',
    iosBundleId: 'com.example.bacalio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jTRMtlf3BB1JABeubsZnece1oaE7yu0',
    appId: '1:173326883920:web:9284a065a7720d4ff74555',
    messagingSenderId: '173326883920',
    projectId: 'b-callio',
    authDomain: 'b-callio.firebaseapp.com',
    storageBucket: 'b-callio.firebasestorage.app',
    measurementId: 'G-XGB2SHKMFT',
  );
}
